### ISSUE TITLE
Convert protocol to PDF and add to repository

### ISSUE THREAD

**Issue by martingerdin** [titco/open-trauma-data-bank#20]

**Comment by Aroke-Anna8** [comment]
Hi Dr. Martin,

PFA the pdf version of the protocol.

[irb-protocol.pdf](https://github.com/titco/open-trauma-data-bank/files/4113717/irb-protocol.pdf)

Thanks.
Anna.

**Comment by martingerdin** [comment]
Please submit this as a pull request and add a comment describing how you went about converting the markdown file to pdf. Thanks!
